name: "Test"
description: "Run tests"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-env

    - name: Run Tests
      run: pnpm test -- --watch=false --ci --reporter=default --passWithNoTests --testTimeout=10000 --testPathPattern=tests/unit
      shell: bash